#!/bin/bash

. "$MUNIN_LIBDIR/plugins/plugin.sh"

if [ "$1" = "autoconf" ]; then
  echo yes
  exit 0
fi

if [ "$1" = "config" ]; then

  echo 'graph_title B route wattage'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel Wattage'
  echo 'graph_info B route wattage'

  echo 'graph_scale no'
  echo 'graph_category sensors'

  echo 'b_route.label B route'
  echo 'b_route.info B route'

  # Last, if run with the "config"-parameter, quit here (don't
  # display any data)
  exit 0
fi

echo -n "b_route.value "
b-route-wattage | cut -d' ' -f1
